services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?defina no .env}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?defina no .env}
      POSTGRES_DB: ${POSTGRES_DB:?defina no .env}
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata:
